# Generated by Django 4.2.4 on 2023-10-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
