# Generated by Django 4.2.4 on 2023-09-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('employee', '0002_alter_employee_category_alter_employee_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='product',
            field=models.ManyToManyField(to='service.products'),
        ),
    ]
