# Generated by Django 4.2.4 on 2023-09-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_alter_employee_category_alter_employee_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
