# Generated by Django 4.2.4 on 2023-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
