# Generated by Django 4.2.4 on 2023-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_isrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isChangePassword',
            field=models.BooleanField(default=False),
        ),
    ]
