# Generated by Django 4.2.4 on 2023-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_ischangepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
