# Generated by Django 4.2.4 on 2023-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'user'), ('counselor', 'counselor'), ('admin', 'admin')], default='user', max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_google', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
