# Generated by Django 4.2.4 on 2023-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee'), ('admin', 'admin')], default='user', max_length=30),
        ),
    ]
