# Generated by Django 4.2.4 on 2023-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
