# Generated by Django 4.2.4 on 2023-10-18 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_address'),
        ('service', '0003_alter_service_service_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_employee_isrequested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.PositiveIntegerField()),
                ('date_of_booking', models.DateField(auto_now_add=True)),
                ('time_of_booking', models.TimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('booked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.products')),
                ('booked_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
