# Generated by Django 4.2.4 on 2023-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
    ]
