# Generated by Django 4.2.4 on 2023-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_is_confirmed_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
