# Generated by Django 4.2.4 on 2023-10-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_service_date_booking_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chat_flag',
            field=models.BooleanField(default=False),
        ),
    ]
