# Generated by Django 4.2.4 on 2023-11-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_feedback_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='booking_id',
        ),
    ]
