# Generated by Django 4.2.4 on 2023-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_feedback_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.IntegerField(null=True),
        ),
    ]
