# Generated by Django 4.2.4 on 2023-08-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('category_des', models.CharField(max_length=250)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='category_img')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_des', models.CharField(max_length=250)),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_des', models.CharField(max_length=255)),
                ('service_img', models.ImageField(upload_to='services')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.products')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
