# Generated by Django 4.2.4 on 2023-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_charge',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
