# Generated by Django 4.2.4 on 2023-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_charge',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
